# Site settings
title: A
header-img: img/home-bg.jpg
email: az@az.com
description: "Trying out design"
github_username:  azaugg

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
