# Site settings
title: Tech,  bits and bobs
header-img: img/home-bg.jpg
email: azaugg.github@gmail.com 
description: "tech bits and bobs"
github_username:  azaugg

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
